- name: Register repository
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    state: present

- name: Install MySQL5.7
  yum:
    name: "{{ item }}"
    enablerepo: mysql57-community
    state: present
  with_items:
    - mysql-community-server
    - mysql-community-client

- name: Start and autorun MySQL5.7
  service: name=mysqld state=started enabled=yes

- name: Install MySQL-python for ansible
  yum: name=MySQL-python state=present

- name: Check installed
  shell: "mysqladmin --defaults-file=/root/.my.cnf ping | grep alive"
  ignore_errors: true
  register: init_flag

# - name: Get initial password
#   shell: "grep 'password is generated' /var/log/mysqld.log | awk -F'root@localhost: ' '{print $2}'"
#   register: initial_password
#   when: init_flag.rc == 1
#
# # - name: Check MySQL root password
# #   shell: mysqlshow -u root -p {{ initial_password.stdout }}
# #   register: root_check
# #   ignore_errors: true
#
# - name: Change root password
#   shell: >
#     mysql --connect-expired-password -u root -p{{ initial_password.stdout }} -e
#     "set password for root@'localhost' = PASSWORD({{ mysql_root_pass }})"
#   when: init_flag.rc == 1
##  when: root_check.stderr.find('defined') == -1

- name: Get initial password
  script: get_root_password.sh creates=/root/.tmp.my.cnf
  when: init_flag.rc == 1

- name: Change root password
  shell: >
    mysql --defaults-file=/root/.tmp.my.cnf -e
    "alter user 'root'@'localhost' identified by '{{ mysql_root_pass }}'"
  when: init_flag.rc == 1

- name: Save root password
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: init_flag.rc == 1

- name: Clear Anonymous
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost.localdomain
    - localhost
  when: init_flag.rc == 1

- name: Create DB
  mysql_db: name={{ db_name }} state=present
  when: init_flag.rc == 1

- name: Create User
  mysql_user: name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL,GRANT state=present
  when: init_flag.rc == 1
